### ISSUE TITLE
cs-studio/applications: mvn verify Error

### ISSUE THREAD

**Issue by myhippo** [ControlSystemStudio/cs-studio#1885]
Hi, everybody. 
I git clone "cs-studio  cs-studio-thirdparty  diirt  maven-osgi-bundles  org.csstudio.sns" according to the css_book.
mvn verify successfully for "cs-studio/core  cs-studio-thirdparty  diirt  maven-osgi-bundles"
and at last I make "mvn verify" for cs-studio/applications. But there is a following error : 

[INFO] Resolving class path of MavenProject: org.csstudio:org.csstudio.saverestore.git:1.0.0-SNAPSHOT @ /root/Documents/css/testsource4/cs-studio/applications/saverestore/saverestore-plugins/org.csstudio.saverestore.git/pom.xml
[INFO] Computing target platform for MavenProject: org.csstudio:org.csstudio.saverestore.masar:1.0.0-SNAPSHOT @ /root/Documents/css/testsource4/cs-studio/applications/saverestore/saverestore-plugins/org.csstudio.saverestore.masar/pom.xml
[INFO] Resolving dependencies of MavenProject: org.csstudio:org.csstudio.saverestore.masar:1.0.0-SNAPSHOT @ /root/Documents/css/testsource4/cs-studio/applications/saverestore/saverestore-plugins/org.csstudio.saverestore.masar/pom.xml
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.csstudio.saverestore.masar 1.0.0.qualifier
[ERROR]   Missing requirement: org.csstudio.saverestore.masar 1.0.0.qualifier requires 'bundle org.epics.pvaccess 4.0.0' but it could not be found

My development environment is as follows:
[root@204127 cs-studio]# uname -a
Linux 204127 2.6.32-573.el6.x86_64 #1 SMP Thu Jul 23 15:44:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@204127 cs-studio]# mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /usr/local/maven
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: /usr/local/software/jdk1.8.0_91/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-573.el6.x86_64", arch: "amd64", family: "unix"

[root@204127 cs-studio]# git branch -vv
* master 30e366b [origin/master] Merge pull request #1879 from ControlSystemStudio/archive_ea4_1877

Can you help me?
Thank you!

**Comment by willrogers** [comment]
The cs-studio build is currently broken for the reasons described here: https://github.com/ControlSystemStudio/cs-studio/issues/1859.

I hope that this will be resolved by the end of the week.

**Comment by willrogers** [comment]
Hold on, this should already have been fixed.  You are at 30e366b, but `master` is now at 9878102.

Try `git pull origin master` and then build again.

**Comment by kasemir** [comment]
Yes, building from the 'master' branch should mostly work.
Of course there are several ways to do this.
In short, my recipe for the SNS products is here: https://github.com/ControlSystemStudio/org.csstudio.sns/tree/master/build

There is one minor issue, see https://github.com/ControlSystemStudio/cs-studio/pull/1884: We recently deprecated org.csstudio.platform.libs.epics.ui. org.csstudio.vtype.pv.ui offers that functionality for those who want to configure EPICS CA from the preference UI, but to actually get that new plugin into the target platform, you need that pull request.

**Comment by kasemir** [comment]
The pull request mentioned in my last comment has been merged.
The complete chain of
 diirt,
 maven-osgi-bundles,
 cs-studio-thirdparty,
 cs-studio/core,
 cs-studio/applications,
 org.csstudio.sns
builds OK in that order from master.
Remaining issues may be in some product files which still need to be updated, but the original error mentioned for this issue report should be resolved.

**Comment by claudio-rosati** [comment]
Not yet working for me: cs-studio is still broken.

[INFO] Resolving class path of MavenProject: org.csstudio:org.csstudio.platform.libs.hibernate.ui:1.0.0-SNAPSHOT @ <https://jenkins02.esss.lu.se/job/CS-Studio%20Original%2000500%20-%20cs-studio/ws/cs-studio/core/platform/platform-plugins/org.csstudio.platform.libs.hibernate.ui/pom.xml>
[ERROR] Internal error: java.lang.IllegalArgumentException: bundleLocation not found: <https://jenkins02.esss.lu.se/job/CS-Studio%20Original%2000500%20-%20cs-studio/ws/.m2/p2/osgi/bundle/org.csstudio.platform.libs.hibernate/1.0.0.201510091318/org.csstudio.platform.libs.hibernate-1.0.0.201510091318.jar> -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.IllegalArgumentException: bundleLocation not found: <https://jenkins02.esss.lu.se/job/CS-Studio%20Original%2000500%20-%20cs-studio/ws/.m2/p2/osgi/bundle/org.csstudio.platform.libs.hibernate/1.0.0.201510091318/org.csstudio.platform.libs.hibernate-1.0.0.201510091318.jar>
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:168)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: java.lang.IllegalArgumentException: bundleLocation not found: <https://jenkins02.esss.lu.se/job/CS-Studio%20Original%2000500%20-%20cs-studio/ws/.m2/p2/osgi/bundle/org.csstudio.platform.libs.hibernate/1.0.0.201510091318/org.csstudio.platform.libs.hibernate-1.0.0.201510091318.jar>
at org.eclipse.tycho.core.osgitools.EquinoxResolver.loadManifest(EquinoxResolver.java:266)
at org.eclipse.tycho.core.osgitools.EquinoxResolver.newState(EquinoxResolver.java:161)
at org.eclipse.tycho.core.osgitools.EquinoxResolver.newResolvedState(EquinoxResolver.java:69)
at org.eclipse.tycho.core.osgitools.OsgiBundleProject.getResolverState(OsgiBundleProject.java:262)
at org.eclipse.tycho.core.osgitools.OsgiBundleProject.resolveClassPath(OsgiBundleProject.java:164)
at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:130)
at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:95)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
... 11 more
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]




Claudio Rosati
Software Engineer

European Spallation Source ERIC
P.O Box 176, SE-221 00 Lund, Sweden
Visiting address: Tunavägen 24, Lund

Phone: +46 46 888 34 24
Mobile: +46 721 79 24 24
E-mail: claudio.rosati@esss.se<mailto:petra.ribb@esss.se>

www.esss.se<http://www.esss.se/>

[cid:EC9AC9A0-89C5-4CC1-89CE-908054AEC1B2]

**Comment by kasemir** [comment]
Well, I've had several successful builds of the 'master' branch by now.

Your error truly looks like an internal maven problem:
````
[INFO] Resolving class path of MavenProject: org.csstudio:org.csstudio.platform.libs.hibernate.ui:1.0.0-SNAPSHOT @ <https://jenkins02.esss.lu.se/job/CS-Studio%20Original%2000500%20-%20cs-studio/ws/cs-studio/core/platform/platform-plugins/org.csstudio.platform.libs.hibernate.ui/pom.xml>
[ERROR] Internal error: java.lang.IllegalArgumentException: bundleLocation not found: <https://jenkins02.esss.lu.se/job/CS-Studio%20Original%2000500%20-%20cs-studio/ws/.m2/p2/osgi/bundle/org.csstudio.platform.libs.hibernate/1.0.0.201510091318/org.csstudio.platform.libs.hibernate-1.0.0.201510091318.jar> -> [Help 1]
````

In your setup, does it make sense that Maven tries to locate the org.csstudio.platform.libs.hibernate jar from an https://jenkins.. URL?
Could there be a web server issue?
Maybe need to start over after deleting $HOME/.m2/repository?

**Comment by claudio-rosati** [comment]
Hello Kay,

You are right. “Copying” my local build-script into the Jenkins pipelines I forgot to clean the .m2 folder at each run.

Thank you for the suggestion. Now my pipeline works fine.

Best regards,
Claudio


Claudio Rosati
Software Engineer

European Spallation Source ERIC
P.O Box 176, SE-221 00 Lund, Sweden
Visiting address: Tunavägen 24, Lund

Phone: +46 46 888 34 24
Mobile: +46 721 79 24 24
E-mail: claudio.rosati@esss.se<mailto:petra.ribb@esss.se>

www.esss.se<http://www.esss.se/>

[cid:EC9AC9A0-89C5-4CC1-89CE-908054AEC1B2]

**Comment by berryma4** [comment]
okay to close?

**Comment by myhippo** [comment]
it's ok to close!
thank you!
