### ISSUE TITLE
Memory leak from Multistate Symbol Widget

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#2014]
We tracked down a memory leak to the Multistate Symbol Widget.  It appears to happen when the widget is connected to a PV which has a double value.

The attached screen has many symbol widgets.  Each one is attached to the same DLS PV which has a double value.  The image for each is also attached (I've had to rename them to text files).  I've also attached an image of jconsole showing the memory leak.

![jconsole](https://cloud.githubusercontent.com/assets/2440055/21386486/ea8f91fc-c76a-11e6-91f8-11a3e48c5790.png)

[current-svg.txt](https://github.com/ControlSystemStudio/cs-studio/files/666096/current-svg.txt)

[svg-opi.txt](https://github.com/ControlSystemStudio/cs-studio/files/666094/svg-opi.txt)

**Comment by willrogers** [comment]
Bump

**Comment by boryto** [comment]
Hi, we tested the provided OPI on latest Cs-studio sources and we could not reproduce the issue. 
The PV that was used had:
 Native data type: DBF_DOUBLE
 Request type:     DBR_DOUBLE

![image](https://user-images.githubusercontent.com/5550006/30272836-dec3160a-96e5-11e7-9dda-b1f33387700f.png)

Can you confirm that this issue is fixed?

**Comment by mfurseman** [comment]
It looks like we do still have the memory leak as of https://github.com/ControlSystemStudio/cs-studio/commit/ef16b7e8c88bd574685bb1defd71cc7e54583ac5.

As we seem to be getting different behaviour I wonder if we have different implementations of garbage collection. We're running against Oracle Java 1.8.0.141.x86_64, and only have the two memory arguments set for the VM:

-Xmx3072m
-Xms256

![jconsole](https://user-images.githubusercontent.com/5279818/30423031-8bc608a8-9939-11e7-9643-323bd433297d.png)

**Comment by boryto** [comment]
Hi, interesting. 
Can you please provide again the test case (was it taken from here?). The IOC is probably somehow simulated. Can you also include the epics db file, so we can have the same PV. 

TNX

**Comment by mfurseman** [comment]
We had previously used our beam current PV, which is a real machine PV that updates once a second, for the test. I have just retried it with `sim://sin` and the results are the same. It seems that this may be something more detailed to do with garbage collection though, as the JVM does seem to have freed memory eventually.

![jconsole-2](https://user-images.githubusercontent.com/5279818/30428605-22d7d73c-994c-11e7-9eaa-305ffb38594e.png)

**Comment by kasemir** [comment]
What is that tool in the sceenshot? Looks different from jvisualvm and jprofiler, which is what I tend to use.
I agree that details of the GC can be unpredictable. Sometimes the VM will initially use a lot of memory, and after a few hours it decides that much less memory is sufficient.
jvisualvm, jprofiler and also the org.csstudio.utility.sysmon offer a button to trigger GC. If that fails to temporarily free up memory I'd suspect an actual memory leak.

**Comment by boryto** [comment]
Hello, 
I can confirm the memory leak. 
![image](https://user-images.githubusercontent.com/5550006/30580106-ecb5e686-9d0a-11e7-92d1-c5f6124f3b54.png)
There are way to much org.apache.batik.doom.GenericText objects. Now we need to find the root cause of this. 
TNX

**Comment by mfurseman** [comment]
@kasemir, that's jconsole, it seems to be bundled with the Oracle JDK, as well as jvisualvm.

**Comment by boryto** [comment]
Reason for memory leak was loading the new image for every different state (every different value is a new state fro image). With double value there were many different states, so many images were loaded for single instance.
This is fixed by rounding the states for images to double and limiting the number of image states to 50.

**Comment by boryto** [comment]
The fix is made by rounding the double values to long. Non-integer image states make no-sense.  
This was tested with 100 multistate widgets with sim://sine.  There was no increasing memory over the 1/2h period, and the memory was freed by GC after the OPI was closed. 




![image](https://user-images.githubusercontent.com/5550006/32788463-8a542022-c959-11e7-8703-d82f4fc99126.png)

**Comment by willrogers** [comment]
Thanks for fixing this. We will test again once this commit is in our build.
